export const SELECTED_RATES_ON_CHANGE = 'SELECTED_RATES_ON_CHANGE';
export const TRUEFX_DATA_SUCCESS = 'TRUEFX_DATA_SUCCESS';
export const SUBSCRIBE_TO_TRUEFX = 'SUBSCRIBE_TO_TRUEFX';
export const UNSUBSCRIBE_FROM_TRUEFX = 'UNSUBSCRIBE_FROM_TRUEFX';
