export const SELECTED_RATES_ON_CHANGE = 'SELECTED_RATES_ON_CHANGE';
export const TRUEFX_DATA_SUCCESS = 'TRUEFX_DATA_SUCCESS';
export const CONNECT_TO_TRUEFX = 'CONNECT_TO_TRUEFX';
export const DISCONNECT_FROM_TRUEFX = 'DISCONNECT_FROM_TRUEFX';
